### ISSUE TITLE
lab2 замечания

### ISSUE THREAD

**Issue by Andrewbooq** [gpuslave/concurrency#1]
1 Makefile: мы используем с++11, но можно и на 17 собирать, разницы нет.
Но что такое `-pthread` ? Во первых это должно быть в секции для линковщика в `LDFLAGS`, а во вторых нам это не нужно.
А вот через `bash find` собрать имена исходником - интересная идея.
2 #include "thread_pool.cpp" так не делается. Есть исходники, они разделяются на 2 части - header и реализация. В хидере должен быть интерфейс объекта( class в котором прототипы вызовов, данные), реализация в *.c / *.cpp.
директива препроцессора #include "header.h". Объектный файл (который получается из компиляции .cpp) указывается компилятору и линковщику при сборке. Иногда могут быть исключения, например для шаблонов, их реализацию можно писать в хидере, но их обычно выносят отдельно от кода, чтобы не нагромождать.
Надо переделать, разнести.
3 В задании не было сделать thread_safe_queue. Но если сможешь подробно рассказать как это работает - нет проблем. Но всё очень сильно усложнено и перегружено. Всё сильно проще надо. Ты же видел у одногрупников как всё делается. 
4 Вывод не thread_safe, поэтому такая "каша" в выводе, надо допилить
![image](https://github.com/user-attachments/assets/b7fe427e-ea06-4895-928e-2d962a9c9cde)

5 Не хватает пояснений, что рассчитывается, куда сохраняется,...

**Comment by gpuslave** [comment]
Насчет `pthread`:
```
-pthread Define additional macros required for using the POSIX threads library. You
 should use this option consistently for both compilation and linking. This
 option is supported on GNU/Linux targets, most other Unix derivatives, and
 also on x86 Cygwin and MinGW targets.
 ```
Также [stackoverflow](https://stackoverflow.com/questions/23250863/difference-between-pthread-and-lpthread-while-compiling?noredirect=1&lq=1)

**Comment by Andrewbooq** [comment]
Ну хорошо, для компилятора pthread, для линкера lpthread, соглашусь. Но в твоём приложении зачем оно? без него не собирается?
Моё понимание - что явно надо указывать pthread для версии ниже c++11 и в том случае, если ты в приложени используешь pthread_t/pthread_create,...

**Comment by gpuslave** [comment]
Ну да, наверное во второй лабе оно не нужно, лучше это в третьей на самих pthread использовать.

**Comment by gpuslave** [comment]
![image](https://github.com/user-attachments/assets/2a005b60-07a6-4879-98c1-98c53cfacde6)
Кстати, у меня почему-то с выводом все нормально (os - debian).

**Comment by Andrewbooq** [comment]
> Ну да, наверное во второй лабе оно не нужно, лучше это в третьей на самих pthread использовать.

Как показывает практика, с с++11 не надо явно указывать phtread/lpthread. т.е. и для 3/4 оно по идее не надо.

`<< ` не является thread safe. нужно либо отдельный мьютекс делать на вывод в std::cout, либо printf использовать.

**Comment by Andrewbooq** [comment]
у тебя виртуадка? или на реальной машине Debian ? Что hardware_concurrency возвращает?

**Comment by Andrewbooq** [comment]
Просто если виртуалка, там точно потоков > 1 ?

**Comment by gpuslave** [comment]
WSL 2; 12 тредов что и на виндовс.
![image](https://github.com/user-attachments/assets/cc535906-2c16-42e6-92c8-6bb12aa6acaa)

**Comment by Andrewbooq** [comment]
не, это ладно, я про то, что ты же сам назначаешь сколько ядер/потоков отдать в виртуалку

**Comment by gpuslave** [comment]
Ну у меня wsl на всех 12 работает, hardware_concurrency 12 возвращает

**Comment by Andrewbooq** [comment]
где-нибудь здесь 
![image](https://github.com/user-attachments/assets/fdbd1938-94f6-4877-b440-e8c632ac692b)

**Comment by Andrewbooq** [comment]
тогда я не знаю, почему у тебя нет проблем с `<<`

**Comment by gpuslave** [comment]
Ну я просто мьютекс сделаю и все, че там мудрить-то

**Comment by gpuslave** [comment]
Добавил автотесты для thread_pool вот [тут](https://github.com/gpuslave/concurrency/actions/runs/12350064300/job/34462138143), там на машине (ubuntu) 4 потока выделяется, можете посмотреть что там вывод (вкладка `run test`) тоже почему-то работает адекватно

**Comment by gpuslave** [comment]
Последний коммит фиксит немного сиаут, но я посмотрел, что у вас и id мешиться с степами, так что надо переделать на глобальный мут...

**Comment by Andrewbooq** [comment]
Ты напиши мне, когда закончишь все правки и можно будет посмотреть, ок?

**Comment by Andrewbooq** [comment]
Кстати, я наверное не совсем правильно сказал. Сама по себе  операция `<<` атомарна, а несколько подряд идущих команд вывода могут быть прерваны (разбиты). И можно перед выводом собирать строку и одной командой пихать в cout.
вместо 
```
std::cout << "строка 1" << "строка 2" << std::endl;
```
можно
```
std::string str = "строка 1" + "строка 2" + "\n"; // условно как-то так
std::cout << str;
```

**Comment by gpuslave** [comment]
@Andrewbooq Можете смотреть полностью, [на этой ветке](https://github.com/gpuslave/concurrency/tree/1-lab2-%D0%B7%D0%B0%D0%BC%D0%B5%D1%87%D0%B0%D0%BD%D0%B8%D1%8F)

**Comment by Andrewbooq** [comment]
![image](https://github.com/user-attachments/assets/2dc48998-1649-497b-9bee-df6cde0419aa)

**Comment by Andrewbooq** [comment]
я не понял зачем ты в LDFLAGS добавил pthread. Его надо полностью убрать

**Comment by Andrewbooq** [comment]
Давай по списоску.
1 Makefile: pthread можно убрать, без него всё прекрасно собирается в обеих ОС. (Можно оставить, не принципиально, просто это лишняя зависимость, которая не нужна).
2 Уже лучше, но не достаточно. Я имел ввиду так, в .h файле:
```
class thread_pool
{
private:
  std::atomic_bool done;
  threadsafe_queue<std::function<void()>> work_queue;
  std::vector<std::thread> threads;
  join_threads joiner;

  unsigned long thread_count;

  void worker_thread();

public:
  thread_pool();
  ~thread_pool();
  size_t get_threads_count();
  void submit(const std::function<void()> &f);
};
```
а реализация в .cpp
!Плюс посмотри принцип `the rule of zero the rule of five`, его надо применить в своём thread_pool классе.
В threadsafe_queue тоже есть нешаблонные функции, их надо в .cpp вынести. Шаблонные можно оставить в .h (те что с <T>).
3 Подход студента имеет место быть, даже если он не соответствует ожиданиям. Работает, вроде, корректно.
4 Исправлено
5 Не хватает пояснений, что рассчитывается, куда сохраняется. Добавь чуть больше информации, что происходит, что это за цифры мы видим, куда сохраняются,...

**Comment by gpuslave** [comment]
Насчёт 5-ого замечания: 
Я над мейном сделал докстринг, вроде всё понятно объяснено, нет?

**Comment by gpuslave** [comment]
Насчёт 1-ого:
Хорошо, уберу
Насчёт 2-ого:
А разве можно темплейты разносить по файлам, я когда пытался это сделать у меня он не мог сконнектиться с .h файлом

**Comment by gpuslave** [comment]
Поправка насчёт второго:
Увидел что в пуле действительно можно разнести, перепутал с очередью

**Comment by Andrewbooq** [comment]
5. Ты не совсем правильно понял (или я не точно объяснил, сорри). Мне понятно, что и где происходит. Речь идет про user-friendly интерфейс приложения. Кто-то, кто просто пользуется твоей утилитой (приложением), не программист, запускает и что видит? 
```
Custom thread_pool implementation using threadsafe queue
Threads available: 8
0.539954
0.399538
0.503338
...
```
что это за цифры? что считаем? куда сохраняем? что сохраняем? Нужно пояснений в вывод для пользователя добавить инфы.
2. Вообще можно реализацию для шаблонов вынести в .cpp, но это громоздко и не нужно. Но у тебя не все функции шаблонные. 
  node *get_tail()
  bool empty()
и другие

попробуй убрать из h в cpp. Думаю, должно получится

**Comment by gpuslave** [comment]
Теперь всё, понял. Доделаю вечером/завтра

**Comment by Andrewbooq** [comment]
Поправка 2. threadsafe_queue У тебя почти везде шаблонный объект node. Нечего там выносить. Оставь в h файле. 
только thread_pool исправь.

**Comment by gpuslave** [comment]
@Andrewbooq новые исправления подоспели, можете оценивать полностью.

**Comment by Andrewbooq** [comment]
В целом уже близко, еще немного и можно будет сдавать. 
1 Makefile: Исправлено
2 Уже еще лучше, но `thread_pool pool;` в `main` создается и в конце удаляется (нигде не копируется, не перемещается), не понял зачем это?
```
  thread_pool(thread_pool &&other) : done(other.done.load()),
                                     work_queue(std::move(other.work_queue)),
                                     threads(std::move(other.threads)),
                                     joiner(threads),
                                     thread_count(other.thread_count)
  {
    other.done = true;
  }
```
Проблема здесь в том, что операции могут генерировать исключения, надо объявить этот конструктор копирования как `noexcept`(так рекомендует microsoft visual studio) , или просто вместо этого сделать:
```
  thread_pool(thread_pool&&) = delete;
  thread_pool& operator=(thread_pool&&) = delete;
```
3 OK
4 OK
5 Не весь вывод закрыт g_cout_mut. 

А вот здесь поехали разбираться в деталях. std::unique_lock когда используется? какой еще есть подобный примитив синхронизации? Какая между ними разница? Нагугли, напиши ответ, исправь в коде.

**Comment by Andrewbooq** [comment]
![image](https://github.com/user-attachments/assets/75099f4f-cf89-4d4b-a9b1-a729e60a8185)

**Comment by Andrewbooq** [comment]
![image](https://github.com/user-attachments/assets/ffea31af-8ea4-485c-a317-26c641ad8f3a)

https://ru.wikipedia.org/wiki/%D0%9F%D1%80%D0%B0%D0%B2%D0%B8%D0%BB%D0%BE_%D1%82%D1%80%D1%91%D1%85_(C%2B%2B)#%D0%9F%D1%80%D0%B0%D0%B2%D0%B8%D0%BB%D0%BE_%D0%BF%D1%8F%D1%82%D0%B8

**Comment by gpuslave** [comment]
В общем я увидел что я забыл на один из cout накинуть lock... Насчет unique lock я почитал еще раз, заменил на lock guard, насколько я понял он просто легче чем unique, плюсом нам здесь функционал unique lock'a не нужен. Я всегда использовал unique, так что просто привычка.
Кстати, как отдельный вопрос: что такое scoped lock, я читал в книжке, что он используется в cxx17 вместо unique?

**Comment by Andrewbooq** [comment]
1 Makefile: Исправлено
2 OK
3 OK
4 OK
5 OK

Про unique_lock / lock_guard верно. Не надо использовать unique_lock там, где можно обойтись lock_guard.
fileMutex тоже наверно можно lock_guard (в след лабе поправь). 

Ниразу не использовал scoped_lock, но вроде как это lock_guard, только лочит не один мьютекс, а несколько, сохраняя порядок блокировки. 

Тип size_t нужно использовать осторожно. Это платформозависимый тип, в винде и в линухе имеет разный размер. Лучше всего вообще использовать очевидные типы, такие как uint32_t (ну или хотябы unsigned int). В этой лабе не критично, а в следующей могут быть проблемы с размерностью, обрати на это внимание.

**Итог: Лаба готова, можно сдавать**

**Comment by gpuslave** [comment]
А ещё я доделал 3-ю лабу, посмотрите, она вот [здесь](https://github.com/gpuslave/concurrency/tree/lab3/winapi_posix/thread_pool)
