### ISSUE TITLE
Lab3-4 Замечания

### ISSUE THREAD

**Issue by Andrewbooq** [gpuslave/concurrency#2]
@gpuslave :
>А ещё я доделал 3-ю лабу, посмотрите, она вот [здесь](https://github.com/gpuslave/concurrency/tree/lab3/winapi_posix/thread_pool)

**Comment by gpuslave** [comment]
?

**Comment by Andrewbooq** [comment]
1 `#ifdef _WIN32` только? Пойдет, но и _WIN64 тоже. Там, кстати, если под 64 собираешь куча ворнингов высыпается с ковертацией типов. Ну это так, если интересно покопаться
2 Не используешь средства диагностики. GetLastError(), errno. Создание потока может обломаться. Надо проверить результат, в случае ошибки получить доп код, вывести диагностику. Мьютексы ты вроде не создаешь WinAPI/POSIX, там нечего проверять.
3 Я знаю, что на лекции говорил, что поток, созданный через _brginthreadex надо завершать _endthreadex. Но мы с Вафиным читали вместе MSDN документацию по _beginthreadex, и вроде как _endthreadex не надо вызывать из кода самостоятельно, вроде этот вызов будет сделан автоматически. Почитай еще ты, что думаешь? Как ты понял?
 https://learn.microsoft.com/ru-ru/cpp/c-runtime-library/reference/beginthread-beginthreadex?view=msvc-170

В остальном всё ок. Допиливай обработку ошибок, присылай, и можно сдавать.
В пт если будешь сдавать 2, можно будет и эту сдать, если время останется.
Для сдачи 2 и 3-4 учи теорию. Лекции, на которых тебя не было ты значешь, темы по лекциям тоже. Будут вопросы - пиши.

**Comment by gpuslave** [comment]
1. Зачем еще win64 делать, если:
```
_WIN32 Defined as 1 when the compilation target is 32-bit ARM, 64-bit ARM, x86, or x64. Otherwise, undefined.

_WIN64 Defined as 1 when the compilation target is 64-bit ARM or x64. Otherwise, undefined.
```

**Comment by Andrewbooq** [comment]
НЕ Соглашусь
![image](https://github.com/user-attachments/assets/5dd4e308-e2ba-4172-aee0-7e53e4e3ba3f)
![image](https://github.com/user-attachments/assets/549e625f-8220-4cf8-bc61-959070009c9f)

**Comment by Andrewbooq** [comment]
А это развлечься от скуки. это если под х64 собрать. size_t платформозависимый тип, его лучше вообще не использовать.
![image](https://github.com/user-attachments/assets/1d878e40-c124-4c2b-b0dd-691586d339a7)

**Comment by Andrewbooq** [comment]
Возможно нам и не надо х64, но работает не так как ты описал. А так:
_WIN64 включает _WIN32
_WIN32 НЕ включает _WIN64

**Comment by gpuslave** [comment]
> 1. Зачем еще win64 делать, если:
> 
> ```
> _WIN32 Defined as 1 when the compilation target is 32-bit ARM, 64-bit ARM, x86, or x64. Otherwise, undefined.
> 
> _WIN64 Defined as 1 when the compilation target is 64-bit ARM or x64. Otherwise, undefined.
> ```

Интересно почему тогда в документации написано вот это, ну ладно

**Comment by gpuslave** [comment]
![image](https://github.com/user-attachments/assets/4688103e-d607-477d-9ccf-b9f96891d6b6)
Действительно, endthreadex вызывается само:
```
...Call _endthreadex explicitly to terminate a thread.
..._endthreadex is called automatically when the thread returns...
...calling _endthreadex helps ensure correct recovery of resources...
```
Если коротко, то вызывать _endthreadex нужно для точной работы, однако оно вызывается само после возврата из функции потока.

**Comment by gpuslave** [comment]
@Andrewbooq я сделал error handling в [c49a768](https://github.com/gpuslave/concurrency/commit/c49a7685208815ab97bfd874f5dd7ddb05598182) , вы зачли или еще не проверяли?

**Comment by Andrewbooq** [comment]
Не зачёл и не проверял, ждал исправления 2 пункта, сейчас посмотрю.

**Comment by Andrewbooq** [comment]
о5 у тебя вывод без g_cout_mut?

**Comment by Andrewbooq** [comment]
Закоменченый код не нужен в репозитории, не надо заливать хлам. Если это не осмысленный комментарий то ему не место в репе.

**Comment by Andrewbooq** [comment]
2 errno в винде? Хоть, наверно, это и должно работать, в смысле константа поддерживается, но не уверен, что она заполняется корректно, я кстати так ниразу не пробовал. Всё же в винде надо стандартный виндовый механизм использовать GetLastError()
А вот этот код не правильный. В какой момент происходит очистка значения errno? А если первый поток не создался, а остальные создаются корректно? 
```
int err = errno;
      if (err != 0 || newthread == nullptr)
```
Откуда эта информация? `err != 0` ????

**Comment by Andrewbooq** [comment]
В остальном всё ОК

**Comment by gpuslave** [comment]
У меня почему-то GetLastError стабильно возвращает 126 либо всегда, хоть и поток создался, либо из первого создания потока 126, остальное 0. 
Не понимаю почему.

**Comment by gpuslave** [comment]
> о5 у тебя вывод без g_cout_mut?

А там он не нужен вроде, эти выводы обрабатываются главным потоком, так что исполнение прямое получается.

**Comment by Andrewbooq** [comment]
>А там он не нужен вроде, эти выводы обрабатываются главным потоком, так что исполнение прямое получается.

Маин поток может быть прерван запущенными тредами уже к этому моменту, если обломилось создание не первого. нет?

Может это поможет
![image](https://github.com/user-attachments/assets/339f4471-4164-4f93-8c1b-00b1e29e53e6)
Как будто чего-то не находит.

Сделай через getlasterror, я у себя запущу. И в принципе, разрешаю сдаваться с этой проблемой, если код будет верный.

**Comment by gpuslave** [comment]
[589b59f](https://github.com/gpuslave/concurrency/commit/589b59f26f206835f8456781510cd9d9d1fb53f7)
Почему так не пойму... Самое главное функция обработки данных работает нормально, нужные числа записываются в файл.
![image](https://github.com/user-attachments/assets/8cd0616d-92f9-4b0d-8af6-649450380d42)

**Comment by gpuslave** [comment]
> Сделай через getlasterror, я у себя запущу. И в принципе, разрешаю сдаваться с этой проблемой, если код будет верный.
@Andrewbooq

**Comment by gpuslave** [comment]
Посмотрите пожалуйста :3 @Andrewbooq

**Comment by Andrewbooq** [comment]
![image](https://github.com/user-attachments/assets/709c0bbd-4756-4fd5-bbf5-beb20293009a)

**Comment by Andrewbooq** [comment]
![image](https://github.com/user-attachments/assets/8fa72987-a469-44f3-aad5-109254b9d7eb)

**Comment by Andrewbooq** [comment]
Microsoft Visual Studio 2019 - всё ок. Что-то твоя Visual Studio Code при сборке косячит похоже. В Винде работает, код на вскидку корректен. Сейчас в Линухе гляну

**Comment by Andrewbooq** [comment]
![image](https://github.com/user-attachments/assets/e920254e-dc77-4153-8b7e-22084e339a72)

**Comment by gpuslave** [comment]
В общем я не заметил, что засунул инициализацию DWORD не в #ifdef для win...
Косячок вышел...
[de7a8bd](https://github.com/gpuslave/concurrency/commit/de7a8bdb4d7cfcecebd8648b5605140ca9a559fa) исправил @Andrewbooq

**Comment by Andrewbooq** [comment]
Всё хорошо, можно сдавать
